#!/bin/bash
echo "🧪 Тестирование сайта Методика Кофе"
echo "=================================="
echo "1. Проверка HTTP статуса:"
curl -s -o /dev/null -w "%{http_code}" https://metodika-coffee.ru && echo " - OK"
echo ""
echo "2. Проверка загрузки JS:"
curl -s -o /dev/null -w "%{http_code}" https://metodika-coffee.ru/static/js/main. | grep -q 200 && echo "✅ JS файлы загружаются" || echo "❌ Проблема с JS"
echo ""
echo "3. Проверка API:"
curl -s https://metodika-coffee.ru/api/test | grep -q "OK" && echo "✅ API работает" || echo "❌ API не отвечает"
echo ""
echo "4. Проверка логов backend:"
pm2 logs metodika-orders-api --lines 5 --nostream 2>/dev/null | tail -1 | grep -q "методika" && echo "✅ Backend запущен" || echo "❌ Backend не работает"
echo ""
echo "5. Проверка прав доступа:"
ls -la /opt/metodika-coffee/frontend/build/static/js/main.*.js 2>/dev/null | grep -q "www-data" && echo "✅ Права верны" || echo "❌ Неправильные права"
echo ""
echo "📋 Для полной проверки откройте https://metodika-coffee.ru в браузере"
