FROM python:3.11-slim
WORKDIR /app
# Пропускаем обновление pip и устанавливаем пакеты с большим таймаутом
RUN pip install --no-cache-dir --default-timeout=300 fastapi==0.104.1 uvicorn[standard]==0.24.0 httpx==0.25.1
COPY ./app/main.py .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
